apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-secret-manager"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete", "update", "list"]